### ISSUE TITLE
undefined method `partial?' for nil:NilClass

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/bitcoinrb#44]
Error occured in regtest mode.

```
I, [2019-05-31T16:29:19.824022 #158 #47033197926660]  INFO -- : [172.28.3.1:18444] process command inv.
I, [2019-05-31T16:29:19.824139 #158 #47033197926660]  INFO -- : receive inv message.
I, [2019-05-31T16:29:19.824174 #158 #47033197926660]  INFO -- : receive block= 1, txs: 0
I, [2019-05-31T16:29:19.824213 #158 #47033197926660]  INFO -- : send message getdata
I, [2019-05-31T16:29:19.828192 #158 #47033197923780]  INFO -- : [172.28.3.4:18444] process command headers.
I, [2019-05-31T16:29:19.828324 #158 #47033197923780]  INFO -- : receive headers message.
I, [2019-05-31T16:29:19.828442 #158 #47033197923780]  INFO -- : append header 3a140cfb1851c1e56d3d0db34bd5da00b1469e71494ec58a92594548356d9d5c
I, [2019-05-31T16:29:19.829012 #158 #47033197923780]  INFO -- : [172.28.3.4:18444] start block header download.
I, [2019-05-31T16:29:19.829118 #158 #47033197923780]  INFO -- : send message getheaders
I, [2019-05-31T16:29:19.830995 #158 #47033197928180]  INFO -- : [172.28.3.2:18444] process command inv.
I, [2019-05-31T16:29:19.831128 #158 #47033197928180]  INFO -- : receive inv message.
I, [2019-05-31T16:29:19.831221 #158 #47033197928180]  INFO -- : receive block= 1, txs: 0
I, [2019-05-31T16:29:19.831493 #158 #47033197928180]  INFO -- : send message getdata
I, [2019-05-31T16:29:19.831664 #158 #47033197928180]  INFO -- : [172.28.3.1:18444] process command merkleblock.
I, [2019-05-31T16:29:19.833169 #158 #47033197928180]  INFO -- : receive merkle block message. {"hashes":["36a39ed285a4ffdb141c16af1eb1029bf18a18a7fdc54c70561d9371714f0c74"],"header":"#<Bitcoin::BlockHeader:0x0000558d89b37a88>","tx_count":1,"flags":"01"}
I, [2019-05-31T16:29:19.838089 #158 #47033197928180]  INFO -- : [172.28.3.1:18444] process command tx.
I, [2019-05-31T16:29:19.848502 #158 #47033197881160]  INFO -- : [172.28.3.3:18444] process command inv.
I, [2019-05-31T16:29:19.848708 #158 #47033197881160]  INFO -- : receive inv message.
I, [2019-05-31T16:29:19.848793 #158 #47033197881160]  INFO -- : receive block= 1, txs: 0
I, [2019-05-31T16:29:19.848877 #158 #47033197881160]  INFO -- : send message getdata
I, [2019-05-31T16:29:19.849989 #158 #47033197928180]  INFO -- : receive tx message. {"tx":"#<Bitcoin::Tx:0x0000558d892c73f8>","use_segwit":false}
E, [2019-05-31T16:29:19.920867 #158 #47033187231140] ERROR -- : error occurred. undefined method `partial?' for nil:NilClass
E, [2019-05-31T16:29:19.921193 #158 #47033187231140] ERROR -- : ["/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/merkle_tree.rb:106:in `next_partial'", "/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/merkle_tree.rb:37:in `block in build_partial'", "/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/merkle_tree.rb:31:in `each'", "/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/merkle_tree.rb:31:in `build_partial'", "/home/wallet/app/lib/bitcoin/wallet/utxo_handler.rb:80:in `save_tx_position'", "/home/wallet/app/lib/bitcoin/wallet/utxo_handler.rb:73:in `merkleblock'", "/home/wallet/app/lib/bitcoin/wallet/utxo_handler.rb:17:in `update'", "/usr/local/lib/ruby/2.5.0/observer.rb:197:in `block in notify_observers'", "/usr/local/lib/ruby/2.5.0/observer.rb:196:in `each'", "/usr/local/lib/ruby/2.5.0/observer.rb:196:in `notify_observers'", "/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/network/peer.rb:195:in `handle_merkle_block'", "/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/network/message_handler.rb:229:in `on_merkle_block'", "/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/network/message_handler.rb:94:in `handle_command'", "/usr/local/bundle/bundler/gems/bitcoinrb-1ef6eaf9d15a/lib/bitcoin/network/message_handler.rb:46:in `block in defer_handle_command'", "/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'"]
I, [2019-05-31T16:29:19.921350 #158 #47033187231140]  INFO -- : close connection with 172.28.3.4:18444. terminate
I, [2019-05-31T16:29:19.921460 #158 #47033187231140]  INFO -- : close connection with 172.28.3.1:18444. terminate
I, [2019-05-31T16:29:19.921545 #158 #47033187231140]  INFO -- : close connection with 172.28.3.2:18444. terminate
I, [2019-05-31T16:29:19.921635 #158 #47033187231140]  INFO -- : close connection with 172.28.3.3:18444. terminate
I, [2019-05-31T16:29:19.921729 #158 #47033187231140]  INFO -- : unbind. 172.28.3.1:18444
I, [2019-05-31T16:29:19.922016 #158 #47033187231140]  INFO -- : unbind. 172.28.3.4:18444
I, [2019-05-31T16:29:19.922383 #158 #47033187231140]  INFO -- : unbind. 172.28.3.2:18444
I, [2019-05-31T16:29:19.925973 #158 #47033187231140]  INFO -- : unbind. 172.28.3.3:18444

```

**Comment by Yamaguchi** [comment]
```
getblock 3a140cfb1851c1e56d3d0db34bd5da00b1469e71494ec58a92594548356d9d5c
{
  "hash": "3a140cfb1851c1e56d3d0db34bd5da00b1469e71494ec58a92594548356d9d5c",
  "confirmations": 5,
  "strippedsize": 228,
  "size": 264,
  "weight": 948,
  "height": 795,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "740c4f7171931d56704cc5fda7188af19b02b11eaf161c14dbffa485d29ea336",
  "tx": [
    "740c4f7171931d56704cc5fda7188af19b02b11eaf161c14dbffa485d29ea336"
  ],
  "time": 1559287759,
  "mediantime": 1559287739,
  "nonce": 1,
  "bits": "207fffff",
  "difficulty": 4.656542373906925e-10,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000000638",
  "nTx": 1,
  "previousblockhash": "0f3e40d91789b9ff5eb8ecd056b48c10ad4fa89662276b638133ef26f2e831d9",
  "nextblockhash": "5aebda1e678be1566fad91cf353969700bbbe66bd9065db6b1dcf3a7f980ad23"
}
```

**Comment by Yamaguchi** [comment]
```
receive merkle block message. {"hashes":["36a39ed285a4ffdb141c16af1eb1029bf18a18a7fdc54c70561d9371714f0c74"],"header":"#<Bitcoin::BlockHeader:0x0000558d89b37a88>","tx_count":1,"flags":"01"}
```

hashes "36a39ed285a4ffdb141c16af1eb1029bf18a18a7fdc54c70561d9371714f0c74" is merkle root (= hash of coinbase tx) of block "3a140cfb1851c1e56d3d0db34bd5da00b1469e71494ec58a92594548356d9d5c"

**Comment by Yamaguchi** [comment]
以下のフローで発生しているように見える。

1. bloom filterによるtxの検出で、 偽陽性によってcoinbase txを誤検出する。
2. アプリ側でそのハッシュに対して、```MerkleTree.build_partial(tx_count, hashes, flags)```を呼び出している。
3. そのブロックがcoinbase txのみの場合、上記の呼び出しが失敗する。
(rootノードに対するNode#next_partialで、rootに対するleft、rightがnilのため?)

ルートノードのみの```MerkleTree.build_partial(tx_count, hashes, flags)```の呼び出しがそのそも想定していないでしょうか？
